behaviors:
  LaserDodge:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.002
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 5
      num_layers: 1
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 20000
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 12500
    threaded: true